# Generated by Django 2.0.4 on 2018-04-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GradeName', models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='mainContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('question', models.TextField()),
                ('Answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=126)),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='SubjectLinked',
            field=models.ManyToManyField(to='webapp.Subject'),
        ),
    ]
