# Generated by Django 2.0.4 on 2018-04-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180426_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True)),
                ('answer', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='question',
        ),
    ]
