# Generated by Django 2.0.4 on 2018-04-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180426_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='topic',
            field=models.ManyToManyField(to='webapp.Topic'),
        ),
    ]
