# Generated by Django 2.0.4 on 2018-04-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_subject_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='TopictLinked',
            field=models.ManyToManyField(to='webapp.Topic'),
        ),
    ]
