# Generated by Django 2.0.4 on 2018-04-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_subject_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='TopictLinked',
        ),
        migrations.AddField(
            model_name='subject',
            name='TopictLinked',
            field=models.ManyToManyField(to='webapp.Topic'),
        ),
    ]
